title: digisea
description: Buying Intelligence for Maritime and Logistics
baseurl: "/digisea"
url: "https://sasatass.github.io"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Include the assets directory
include:
  - assets

# Sass settings (if you're using Sass)
sass:
  sass_dir: _sass
  style: compressed
